importing libraries

In [1]:
import numpy as np
import pandas as pd

Series is 1D and DataFrames are 2D objects
But why?
And what exactly is index?

In [2]:
# can we have multiple index? Let's try
X = [('cs',18),('cs',28),('cs',38),('med',18),('med',28),('med',38)]
mySeries = pd.Series([1,2,3,4,5,6], index=X)
mySeries

(cs, 18)     1
(cs, 28)     2
(cs, 38)     3
(med, 18)    4
(med, 28)    5
(med, 38)    6
dtype: int64

In [3]:
#problem : we cant get value using one index, because its bonded deptt+year
#X['ics']

In [4]:
#the Solution: we use multi_indexing known as Hierarchical indexing

#using function called pd.multiindex.from_tuples()
multi_index = pd.MultiIndex.from_tuples(X)
multi_index.levels[0]

Index(['cs', 'med'], dtype='object')

In [5]:
#second method is pd.multiindex.from_product()
pd.MultiIndex.from_product([['cs','med'],[18,28,38,48,58,68]])

MultiIndex([( 'cs', 18),
            ( 'cs', 28),
            ( 'cs', 38),
            ( 'cs', 48),
            ( 'cs', 58),
            ( 'cs', 68),
            ('med', 18),
            ('med', 28),
            ('med', 38),
            ('med', 48),
            ('med', 58),
            ('med', 68)],
           )

In [6]:
# creating a series with multiindex object
Y = pd.Series([1,2,3,4,5,6], index=multi_index)
Y

cs   18    1
     28    2
     38    3
med  18    4
     28    5
     38    6
dtype: int64

In [7]:
#now its possible we can fetch a hierarchal result relates to single index
Y['cs']

18    1
28    2
38    3
dtype: int64

In [8]:
Y['med']

18    4
28    5
38    6
dtype: int64

In [9]:
#converting 2D series into df
temp = Y.unstack()
temp

     18  28  38
cs    1   2   3
med   4   5   6

In [10]:
#converting a df into multiindexing series
temp.stack()

cs   18    1
     28    2
     38    3
med  18    4
     28    5
     38    6
dtype: int64

In [11]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12]
    ],
    index = multi_index,
    columns = ['avg_package','students']
)

branch_df1

        avg_package  students
cs  18            1         2
    28            3         4
    38            5         6
med 18            7         8
    28            9        10
    38           11        12

In [12]:
branch_df1['students']

cs   18     2
     28     4
     38     6
med  18     8
     28    10
     38    12
Name: students, dtype: int64

In [13]:
branch_df1['avg_package']

cs   18     1
     28     3
     38     5
med  18     7
     28     9
     38    11
Name: avg_package, dtype: int64

In [14]:
# Are columns really different from index?

In [15]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0]
    ],
    index = [2019,2020,2021],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0

In [16]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [17]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0]
    ],
    index = multi_index,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

             delhi               mumbai
       avg_package students avg_package students
cs  18           1        2           0        0
    28           3        4           0        0
    38           5        6           0        0
med 18           9       10           0        0
    28          11       12           0        0
    38          13       14           0        0

In [18]:
branch_df1

        avg_package  students
cs  18            1         2
    28            3         4
    38            5         6
med 18            7         8
    28            9        10
    38           11        12

In [19]:
branch_df1.unstack().stack()

/tmp/ipykernel_3865/1991893145.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

        avg_package  students
cs  18            1         2
    28            3         4
    38            5         6
med 18            7         8
    28            9        10
    38           11        12

In [20]:
branch_df2.stack().stack().unstack()

/tmp/ipykernel_3865/3800539478.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df2.stack().stack().unstack()

                  delhi  mumbai
2019 avg_package      1       0
     students         2       0
2020 avg_package      3       0
     students         4       0
2021 avg_package      5       0
     students         6       0

In [21]:
branch_df3.unstack().stack()

/tmp/ipykernel_3865/3002268404.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df3.unstack().stack()

             delhi               mumbai
       avg_package students avg_package students
cs  18           1        2           0        0
    28           3        4           0        0
    38           5        6           0        0
med 18           9       10           0        0
    28          11       12           0        0
    38          13       14           0        0

### Working with multiindex dataframes

*   head and tail

*  shape

*   info

*   duplicate

In [22]:
# Extracting rows single
branch_df1

        avg_package  students
cs  18            1         2
    28            3         4
    38            5         6
med 18            7         8
    28            9        10
    38           11        12

In [23]:
branch_df1.loc[('cs',18)]

avg_package    1
students       2
Name: (cs, 18), dtype: int64

In [24]:
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0

In [25]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [26]:
branch_df3

             delhi               mumbai
       avg_package students avg_package students
cs  18           1        2           0        0
    28           3        4           0        0
    38           5        6           0        0
med 18           9       10           0        0
    28          11       12           0        0
    38          13       14           0        0

In [27]:
branch_df3.loc[('cs',18)]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: (cs, 18), dtype: int64

In [28]:
#multiple
branch_df3.loc[('cs',28):('med',28)]

             delhi               mumbai
       avg_package students avg_package students
cs  28           3        4           0        0
    38           5        6           0        0
med 18           9       10           0        0
    28          11       12           0        0

In [29]:
# Extracting both
branch_df3.iloc[[0,4],[1,2]]

          delhi      mumbai
       students avg_package
cs  18        2           0
med 28       12           0

In [30]:
# sort index
# both -> descending -> diff order
# based on one level
branch_df3.sort_index(ascending=False)
branch_df3.sort_index(ascending=[False,True])
branch_df3.sort_index(level=0,ascending=[False])

             delhi               mumbai
       avg_package students avg_package students
med 18           9       10           0        0
    28          11       12           0        0
    38          13       14           0        0
cs  18           1        2           0        0
    28           3        4           0        0
    38           5        6           0        0

In [32]:
 #multiindex dataframe(col) -> transpose
branch_df3.transpose()

                   cs       med
                   18 28 38  18  28  38
delhi  avg_package  1  3  5   9  11  13
       students     2  4  6  10  12  14
mumbai avg_package  0  0  0   0   0   0
       students     0  0  0   0   0   0

In [33]:
# swaplevel
branch_df3.swaplevel(axis=1)

       avg_package students avg_package students
             delhi    delhi      mumbai   mumbai
cs  18           1        2           0        0
    28           3        4           0        0
    38           5        6           0        0
med 18           9       10           0        0
    28          11       12           0        0
    38          13       14           0        0